### ISSUE TITLE
depends on packages stored on the authors local hard drive ?

### ISSUE THREAD

**Issue by timbophillips** [chuckjaz/vscode-ng-template-service#1]
I would like to try this extension but it appears its only set up to work on chuckj's computer?

"@angular/language-service": "file:///Users/chuckj/src/angular/dist/packages-dist/language-service"
"@angular/compiler": "file:///Users/chuckj/src/angular/dist/packages-dist/compiler",
"@angular/compiler-cli": "file:///Users/chuckj/src/angular/dist/packages-dist/compiler-cli",
"@angular/core": "file:///Users/chuckj/src/angular/dist/packages-dist/core",
"@angular/tsc-wrapped": "file:///Users/chuckj/src/angular/dist/tools/@angular/tsc-wrapped",

**Comment by chuckjaz** [comment]
This was temporary until the language service was made part of the master branch of Angular. This should now be fixed.
