### ISSUE TITLE
Cant find version 0.0.10

### ISSUE THREAD

**Issue by kukjevov** [chuckjaz/vscode-ng-template-service#7]
Hi Chuck.

I have watch for this project and i have received email:

Alpha release 0.0.10

To test install the .vsix file using "Install from VSIX.." in the "Extensions" tab's menu.

This release has known issues. Use at your own risk.

Please submit issues you have with this release to https://github.com/chuckjaz/vscode-ng-template-service/issues.

When i click on link https://github.com/chuckjaz/vscode-ng-template-service/releases/tag/0.0.10 github returns 404 not found. 

And one more thing, i cloned repository and tried to build vsix by myself, but without success. 
Both branches master and release-tags fails to build during ./build.sh on tsc errors.

release-tags: src/editorServices.ts(2036,21): error TS2346: Supplied parameters do not match any signature of call target.

master: src/extension.ts(5,57): error TS2307: Cannot find module 'vscode'.

I would like to try this extensions lookes awesome, but right now i still cant.

**Comment by chuckjaz** [comment]
The 0.0.10 release had issues and I retracted it.

The error above was due to a change in Angular that I just fixed.

**Comment by chuckjaz** [comment]
0.0.10 is now back, updated and, hopefully, more stable.
